import { DEFAULT_VIDEO_CODE } from "../../../BackgroundProvider";
import type { Team } from "../../../interfaces";

export const teams: Team[] = [
    {
        id: 0,
        name: "NHLHUB",
        abbrev: "NHL",
        logo: "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/Avatars/NHL_Logo.svg",
        selectionLogoScale: 0.75,
        primaryColor: "#000",
        primaryColorRgb: "231, 232, 231",
        secondaryColor: "#E7E8E7",
        videoCode: DEFAULT_VIDEO_CODE,
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/nhl-wallpaper.jpg",
        goalAnimationCode: "",
        emojis: ["🏒", "🥅", "🏆", "🚨"],
    },
    {
        id: 1,
        name: "Anaheim Ducks",
        abbrev: "ANA",
        logo: "https://assets.nhle.com/logos/nhl/svg/ANA_light.svg",
        primaryColor: "#f47a38",
        primaryColorRgb: "244, 122, 56",
        secondaryColor: "#000",
        videoCode: "7v2TspPx_qM",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/ducks.png",
        goalAnimationCode: "ROYnAU_0AWc",
        emojis: ["🦆", "🧡", "🏒", "❄️"],
    },
    {
        id: 2,
        name: "Boston Bruins",
        abbrev: "BOS",
        logo: "https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026",
        primaryColor: "#ffb81c",
        primaryColorRgb: "255, 184, 28",
        secondaryColor: "#000",
        videoCode: "jx9GsSpLdmM",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/bruins.png",
        goalAnimationCode: "kHE2JoekSNk",
        emojis: ["🐻", "🟡", "🏒", "💪"],
    },
    {
        id: 3,
        name: "Buffalo Sabres",
        abbrev: "BUF",
        logo: "https://assets.nhle.com/logos/nhl/svg/BUF_light.svg",
        primaryColor: "#003087",
        primaryColorRgb: "0, 48, 135",
        secondaryColor: "#ffb81c",
        videoCode: "rbKi6lMKCvc",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/sabres.png",
        goalAnimationCode: "GRsptYdx0gA",
        emojis: ["🗡️", "🦬", "💙", "🏒"],
    },
    {
        id: 4,
        name: "Calgary Flames",
        abbrev: "CGY",
        logo: "https://assets.nhle.com/logos/nhl/svg/CGY_light.svg",
        primaryColor: "#d2001c",
        primaryColorRgb: "210, 0, 28",
        secondaryColor: "#ffb81c",
        videoCode: "H-ElcWwFVQQ",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/flames.png",
        goalAnimationCode: "tC4pSEGZ4Nk",
        emojis: ["🔥", "🔴", "🏒", "💛"],
    },
    {
        id: 5,
        name: "Carolina Hurricanes",
        abbrev: "CAR",
        logo: "https://assets.nhle.com/logos/nhl/svg/CAR_light.svg",
        primaryColor: "#cc0000",
        primaryColorRgb: "204, 0, 0",
        secondaryColor: "#000",
        videoCode: "hnOtrGIRAKQ",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/canes.png",
        goalAnimationCode: "F40DKRJHbvA",
        emojis: ["🌪️", "🌀", "🔴", "🏒"],
    },
    {
        id: 6,
        name: "Chicago Blackhawks",
        abbrev: "CHI",
        logo: "https://assets.nhle.com/logos/nhl/svg/CHI_light.svg?season=20252026",
        primaryColor: "#cf0a2c",
        primaryColorRgb: "207, 10, 44",
        secondaryColor: "#000",
        videoCode: "XIZxDqg4gMk",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/hawks.png",
        goalAnimationCode: "x_JCSKe3C0Q",
        emojis: ["🪶", "🏹", "🔴", "🏒"],
    },
    {
        id: 7,
        name: "Colorado Avalanche",
        abbrev: "COL",
        logo: "https://assets.nhle.com/logos/nhl/svg/COL_light.svg",
        primaryColor: "#6f263d",
        primaryColorRgb: "111, 38, 61",
        secondaryColor: "#236192",
        videoCode: "fhuyQYYiekw",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/avs.png",
        goalAnimationCode: "VZH4S-6ww9M",
        emojis: ["🏔️", "❄️", "💨", "🏒"],
    },
    {
        id: 8,
        name: "Columbus Blue Jackets",
        abbrev: "CBJ",
        logo: "https://assets.nhle.com/logos/nhl/svg/CBJ_light.svg",
        primaryColor: "#002654",
        primaryColorRgb: "0, 38, 84",
        secondaryColor: "#ce1126",
        videoCode: "LCWY0HMKEuk",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/jackets.png",
        goalAnimationCode: "dyewPKAwBE8",
        emojis: ["⭐", "🇺🇸", "🔵", "🏒"],
    },
    {
        id: 9,
        name: "Dallas Stars",
        abbrev: "DAL",
        logo: "https://assets.nhle.com/logos/nhl/svg/DAL_light.svg",
        primaryColor: "#006847",
        primaryColorRgb: "0, 104, 71",
        secondaryColor: "#8f8f8c",
        videoCode: "8CcXpOC5Jz0",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/dallas-stars.png",
        goalAnimationCode: "8QA1hIZQ5HA",
        emojis: ["🦦", "⭐", "🤠", "💚"],
    },
    {
        id: 10,
        name: "Detroit Red Wings",
        abbrev: "DET",
        logo: "https://assets.nhle.com/logos/nhl/svg/DET_light.svg?season=20252026",
        primaryColor: "#ce1126",
        primaryColorRgb: "206, 17, 38",
        secondaryColor: "#fff",
        videoCode: "YFmGEv3Orqw",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/wings.png",
        goalAnimationCode: "sFAwUGj23Wg",
        emojis: ["🪽", "🐙", "🦑", "🔴"],
    },
    {
        id: 11,
        name: "Edmonton Oilers",
        abbrev: "EDM",
        logo: "https://assets.nhle.com/logos/nhl/svg/EDM_light.svg",
        primaryColor: "#041e42",
        primaryColorRgb: "4, 30, 66",
        secondaryColor: "#ff4c00",
        videoCode: "Os7UhSBSJ_0",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/oilers.png",
        goalAnimationCode: "03cpCjcYhlM",
        emojis: ["🛢️", "🔥", "🟠", "🏒"],
    },
    {
        id: 12,
        name: "Florida Panthers",
        abbrev: "FLA",
        logo: "https://assets.nhle.com/logos/nhl/svg/FLA_light.svg",
        primaryColor: "#c8102e",
        primaryColorRgb: "200, 16, 46",
        secondaryColor: "#041e42",
        videoCode: "laUgjOICEas",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/panthers.png",
        goalAnimationCode: "TJdRkgSQp3A",
        emojis: ["🐆", "🌴", "🔴", "🏒"],
    },
    {
        id: 13,
        name: "Los Angeles Kings",
        abbrev: "LAK",
        logo: "https://assets.nhle.com/logos/nhl/svg/LAK_light.svg",
        primaryColor: "#111111",
        primaryColorRgb: "17, 17, 17",
        secondaryColor: "#a2aaad",
        videoCode: "eKZjexqxE9Q",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/kings.png",
        goalAnimationCode: "5nTaXdJmRYg",
        emojis: ["👑", "⚫", "🏒", "✨"],
    },
    {
        id: 14,
        name: "Minnesota Wild",
        abbrev: "MIN",
        logo: "https://assets.nhle.com/logos/nhl/svg/MIN_light.svg",
        primaryColor: "#154734",
        primaryColorRgb: "21, 71, 52",
        secondaryColor: "#ddcba4",
        videoCode: "epPM3wfqeZw",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/wild.png",
        goalAnimationCode: "7bw7laBYa4M",
        emojis: ["🌲", "🐻", "🌲", "🏒"],
    },
    {
        id: 15,
        name: "Montreal Canadiens",
        abbrev: "MTL",
        logo: "https://assets.nhle.com/logos/nhl/svg/MTL_light.svg",
        primaryColor: "#af1e2d",
        primaryColorRgb: "175, 30, 45",
        secondaryColor: "#192168",
        videoCode: "jP0-iOGIkPQ",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/habs.png",
        goalAnimationCode: "qgIOXoHwOeM",
        emojis: ["🇨🇦", "🔴", "🏒", "⚜️"],
    },
    {
        id: 16,
        name: "Nashville Predators",
        abbrev: "NSH",
        logo: "https://assets.nhle.com/logos/nhl/svg/NSH_light.svg",
        primaryColor: "#ffb81c",
        primaryColorRgb: "255, 184, 28",
        secondaryColor: "#041e42",
        videoCode: "MEpSSIcEsjs",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/preds.png",
        goalAnimationCode: "k-tC82siSso",
        emojis: ["🐯", "🦷", "🟡", "🏒"],
    },
    {
        id: 17,
        name: "New Jersey Devils",
        abbrev: "NJD",
        logo: "https://assets.nhle.com/logos/nhl/svg/NJD_light.svg",
        primaryColor: "#ce1126",
        primaryColorRgb: "206, 17, 38",
        secondaryColor: "#000",
        videoCode: "VZFDhKBZeYw",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/devils.png",
        goalAnimationCode: "p9x0Kek9B78",
        emojis: ["😈", "🔥", "🔴", "🏒"],
    },
    {
        id: 18,
        name: "New York Islanders",
        abbrev: "NYI",
        logo: "https://assets.nhle.com/logos/nhl/svg/NYI_light.svg",
        primaryColor: "#00539b",
        primaryColorRgb: "0, 83, 155",
        secondaryColor: "#f47d30",
        videoCode: "UEvg3lXtu1g",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/islanders.png",
        goalAnimationCode: "PGIhQCooVno",
        emojis: ["🏝️", "🔶", "🔵", "🏒"],
    },
    {
        id: 19,
        name: "New York Rangers",
        abbrev: "NYR",
        logo: "https://assets.nhle.com/logos/nhl/svg/NYR_light.svg",
        primaryColor: "#0038a8",
        primaryColorRgb: "0, 56, 168",
        secondaryColor: "#ce1126",
        videoCode: "V26Xn7ns_RU",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/rangers.png",
        goalAnimationCode: "6elwxTD4YGg",
        emojis: ["🗽", "🔴", "🔵", "🏒"],
    },
    {
        id: 20,
        name: "Ottawa Senators",
        abbrev: "OTT",
        logo: "https://assets.nhle.com/logos/nhl/svg/OTT_light.svg",
        primaryColor: "#c52032",
        primaryColorRgb: "197, 32, 50",
        secondaryColor: "#000",
        videoCode: "33ejb_1ax1o",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/sens.png",
        goalAnimationCode: "aJq5cHxLo8Q",
        emojis: ["🛡️", "⚔️", "🔴", "🏒"],
    },
    {
        id: 21,
        name: "Philadelphia Flyers",
        abbrev: "PHI",
        logo: "https://assets.nhle.com/logos/nhl/svg/PHI_light.svg",
        primaryColor: "#f74902",
        primaryColorRgb: "247, 73, 2",
        secondaryColor: "#000",
        videoCode: "HKQlzMUZYSk",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/flyers.png",
        goalAnimationCode: "UpMiLuKEpNM",
        emojis: ["✈️", "🟠", "🔥", "🏒"],
    },
    {
        id: 22,
        name: "Pittsburgh Penguins",
        abbrev: "PIT",
        logo: "https://assets.nhle.com/logos/nhl/svg/PIT_light.svg",
        primaryColor: "#000",
        primaryColorRgb: "0, 0, 0",
        secondaryColor: "#ffb81c",
        videoCode: "RPVRHMNNdy8",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/pens.png",
        goalAnimationCode: "WmyaMOrKbCw",
        emojis: ["🐧", "🟡", "🏒", "❄️"],
    },
    {
        id: 23,
        name: "San Jose Sharks",
        abbrev: "SJS",
        logo: "https://assets.nhle.com/logos/nhl/svg/SJS_light.svg",
        primaryColor: "#006d75",
        primaryColorRgb: "0, 109, 117",
        secondaryColor: "#000",
        videoCode: "klyBq1oylZg",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/sharks.png",
        goalAnimationCode: "zvKywmf0IKw",
        emojis: ["🦈", "🌊", "🟦", "🏒"],
    },
    {
        id: 24,
        name: "Seattle Kraken",
        abbrev: "SEA",
        logo: "https://assets.nhle.com/logos/nhl/svg/SEA_light.svg",
        primaryColor: "#001628",
        primaryColorRgb: "0, 22, 40",
        secondaryColor: "#99d9d9",
        videoCode: "uJzigflr9oA",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/kraken.png",
        goalAnimationCode: "SosdN8ngdIA",
        emojis: ["🔱", "🌊", "🏒"],
    },
    {
        id: 25,
        name: "St. Louis Blues",
        abbrev: "STL",
        logo: "https://assets.nhle.com/logos/nhl/svg/STL_light.svg?season=20252026",
        primaryColor: "#002f87",
        primaryColorRgb: "0, 47, 135",
        secondaryColor: "#ffb81c",
        videoCode: "VdIyLUUdZ_8",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/blues.png",
        goalAnimationCode: "rDYHPJElOo8",
        emojis: ["🎺", "🎶", "💙", "🏒"],
    },
    {
        id: 26,
        name: "Tampa Bay Lightning",
        abbrev: "TBL",
        logo: "https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg",
        primaryColor: "#002868",
        primaryColorRgb: "0, 40, 104",
        secondaryColor: "#fff",
        videoCode: "MtxVWgrlrEI",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/bolts.png",
        goalAnimationCode: "MBxxCDtBXlY",
        emojis: ["⚡", "🌩️", "🔵", "🏒"],
    },
    {
        id: 27,
        name: "Toronto Maple Leafs",
        abbrev: "TOR",
        logo: "https://assets.nhle.com/logos/nhl/svg/TOR_dark.svg",
        primaryColor: "#00205b",
        primaryColorRgb: "0, 32, 91",
        secondaryColor: "#fff",
        videoCode: "ThTIzZXdu7s",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/leafs.png",
        goalAnimationCode: "2_c8ONuwsn0",
        emojis: ["🍁", "🔵", "🏒", "🇨🇦"],
    },
    {
        id: 28,
        name: "Utah Mammoth",
        abbrev: "UTA",
        logo: "https://assets.nhle.com/logos/nhl/svg/UTA_light.svg?season=20252026",
        primaryColor: "#041e42",
        primaryColorRgb: "4, 30, 66",
        secondaryColor: "#ffffff",
        videoCode: "nywcDUsYYGI",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/mammoth.jpg",
        goalAnimationCode: "u7_yCy9vif4",
        emojis: ["🦣", "🏔️", "❄️", "🏒"],
    },
    {
        id: 29,
        name: "Vancouver Canucks",
        abbrev: "VAN",
        logo: "https://assets.nhle.com/logos/nhl/svg/VAN_light.svg",
        primaryColor: "#00205b",
        primaryColorRgb: "0, 32, 91",
        secondaryColor: "#00843d",
        videoCode: "TIv4FSwG5Gg",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/canucks.png",
        goalAnimationCode: "yJkijlLvMLs",
        emojis: ["🐋", "🌊", "🟢", "🏒"],
    },
    {
        id: 30,
        name: "Vegas Golden Knights",
        abbrev: "VGK",
        logo: "https://assets.nhle.com/logos/nhl/svg/VGK_light.svg",
        primaryColor: "#b4975a",
        primaryColorRgb: "180, 151, 90",
        secondaryColor: "#333f42",
        videoCode: "HiPaKJF2Kso",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/knights.png",
        goalAnimationCode: "om53osHrUiA",
        emojis: ["🛡️", "⚔️", "✨", "🏒"],
    },
    {
        id: 31,
        name: "Washington Capitals",
        abbrev: "WSH",
        logo: "https://assets.nhle.com/logos/nhl/svg/WSH_secondary_light.svg",
        primaryColor: "#041e42",
        primaryColorRgb: "4, 30, 66",
        secondaryColor: "#ce1126",
        videoCode: "ElxGE8VDJ0M",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/caps.png",
        goalAnimationCode: "N0QbadOzVMQ",
        emojis: ["🦅", "🏛️", "🔴", "🏒"],
    },
    {
        id: 32,
        name: "Winnipeg Jets",
        abbrev: "WPG",
        logo: "https://assets.nhle.com/logos/nhl/svg/WPG_light.svg",
        primaryColor: "#041e42",
        primaryColorRgb: "4, 30, 66",
        secondaryColor: "#7b303e",
        videoCode: "zPdqw5R033s",
        wallpaper:
            "https://zxjfbybflcnjgjcazcoy.supabase.co/storage/v1/object/public/chat_wallpapers/jets.png",
        goalAnimationCode: "Hdbb3_ScMOM",
        emojis: ["✈️", "🛩️", "🔵", "🏒"],
    },
];
