type UserRole = "admin" | "user";

export type ThemeType = "glass" | "arena" | "original6";

export interface User {
    id: number; // created/generated by me manually
    access_code: string; // created/generated by me manually
    name: string | null; // User entered
    selected_team: Team | null; // User selected
    selected_theme: ThemeType; // Default is "glass"
    avatar_url: string; // created/generated by me manually
    role: UserRole;
    created_at: string; // ISO date
    last_login_at: string | null;
    location: string;
}

export interface Login {
    token: string;
    user: User;
}

export interface Team {
    id: number;
    name: string;
    abbrev: string;
    logo: string;
    selectionLogoScale?: number;
    primaryColor: string;
    secondaryColor: string;
    primaryColorRgb: string;
    videoCode: string;
    wallpaper: string;
    goalAnimationCode: string;
    emojis: string[];
}

export type ChatMessageType = "text" | "gif" | "image" | "siren";
export type ChatReactionType = "like" | "love" | "laugh" | "wow" | "sad";

export interface ChatMessageUser {
    id: number;
    name: string | null;
    avatar_url: string;
    selected_team: Team | null;
}

export interface ChatMessageReadReceipt {
    room_key: string;
    user_id: number;
    last_read_message_id: number;
    last_read_at: string;
    user: ChatMessageUser | null;
}

export interface ChatMessage {
    id: number;
    created_at: string;
    user_id: number;
    room_key: string;
    message_type: ChatMessageType;
    body: string | null;
    media_provider: string | null;
    media_id: string | null;
    media_url: string | null;
    user: ChatMessageUser | null;
    reactions: ChatMessageReaction[];
    read_receipts: ChatMessageReadReceipt[];
}

interface ChatMessageReaction {
    id: number;
    created_at: string;
    message_id: number;
    user_id: number;
    reaction_type: ChatReactionType;
    user: ChatMessageUser | null;
}

export interface ChatTypingEvent {
    roomKey: string;
    user: ChatMessageUser;
    isTyping: boolean;
}

export interface ChatPresenceUpdate {
    roomKey: string;
    users: ChatMessageUser[];
}

export interface ChatReactionUpdate {
    messageId: number;
    reactions: ChatMessageReaction[];
}

export interface ChatReadReceiptUpdate {
    roomKey: string;
    previousLastReadMessageId: number | null;
    readReceipt: ChatMessageReadReceipt | null;
}

export interface ChatMessageDeleteEvent {
    messageId: number;
    roomKey: string;
}

export interface LinkPreview {
    url: string;
    hostname: string;
    siteName: string | null;
    title: string;
    description: string | null;
    imageUrl: string | null;
}
